/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem4;

import java.time.LocalDate;
import java.time.Month;
import java.util.Arrays;
import java.util.DoubleSummaryStatistics;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 *
 * @author eck
 */
class Employee {

    public static enum Gender {

        MALE, FEMALE
    }

    private String name;
    private Gender gender;
    private LocalDate dob;
    private double income;

    //a)
    private UUID employeeID;

    private Employee(String name, Gender gender, LocalDate dob,
            double income) {
        
        this.name = name;
        this.gender = gender;
        this.dob = dob;
        this.income = income;
        this.employeeID = UUID.randomUUID();
    }

    public Employee() {
    }

    //b)

    @Override
    public String toString() {
        return String.format("%s,%s,%s,%f,%s" ,name,gender,dob,income,employeeID);
    }

    public double getIncome() {
        return income;
    }

    public static List<Employee> persons() {
        Employee p1 = new Employee( "Jake", Gender.MALE, LocalDate.of(1971,
                Month.JANUARY, 1), 2343.0);
        Employee p2 = new Employee("Jack", Gender.MALE, LocalDate.of(1972,
                Month.JULY, 21), 7100.0);
        Employee p3 = new Employee( "Jane", Gender.FEMALE, LocalDate.of(1973,
                Month.MAY, 29), 5455.0);
        Employee p4 = new Employee("Jode", Gender.MALE, LocalDate.of(1974,
                Month.OCTOBER, 16), 1800.0);
        Employee p5 = new Employee( "Jeny", Gender.FEMALE, LocalDate.of(1975,
                Month.DECEMBER, 13), 1234.0);
        Employee p6 = new Employee( "Jason", Gender.MALE, LocalDate.of(1976,
                Month.JUNE, 9), 3211.0);

        List<Employee> persons = Arrays.asList(p1, p2, p3, p4, p5, p6);

        return persons;
    }

    public static void statistics() {
        //c)
        double sumOfIncomes = 0;
        for (int i = 0; i < persons().size(); i++) {
            sumOfIncomes += persons().get(i).income;
        }
        System.out.println("The income of the employees, generated by the persons() function is: " + sumOfIncomes);
    }
    public void personsStatsByGenderCount(){
        int Males = 0;
        int Females = 0;
        for (int i = 0; i < persons().size() ; i++) {
            if(persons().get(i).gender == Gender.MALE) {
                Males++;
            }
            else if(persons().get(i).gender == Gender.FEMALE){
                Females++;
            }
        }
        System.out.println("The count of Males is: " + Males + " and the count of females is: " + Females);
    }
    public void personsStatsByGenderList(){
        int Males = 0;
        String maleNames ="";
        int Females = 0;
        String femaleNames ="";
        for (int i = 0; i < persons().size() ; i++) {
            if(persons().get(i).gender == Gender.MALE) {
                Males++;
                maleNames += persons().get(i).name;
            }
            else if(persons().get(i).gender == Gender.FEMALE){
                Females++;
                femaleNames += persons().get(i).name;
            }
        }
        System.out.println("The count of Males is: " + Males +", with names: " +maleNames
                + " and the count of females is: " + Females +", with names: " + femaleNames);
    }
}

